### ISSUE TITLE
Error: Can't find Python executable "python", you can set the PYTHON env variable

### ISSUE THREAD

**Issue by cliffordfajardo** [sentialx/extract-file-icon#3]
When running `npm install extract-file-icon` for the first time on my Windows 10 machine I recieved the following error:

```
Can't find Python executable "python", you can set the PYTHON env variable
```
**Update**:
 I'd forgot this was an entirely new Windows machine I'm on, so I don't have python installed on this system. 😅 

Hmm need too look to see if there's a way around this python dependency. I could see this dependency being problematic if this a package is used in an electron app, which tries to call this package on a Windows computer that doesn't have python installed.

Stack Trace:

<details>

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'rebuild'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.2.0
4 verbose run-script [ 'prerebuild', 'rebuild', 'postrebuild' ]
5 info lifecycle extract-file-icon@0.3.1~prerebuild: extract-file-icon@0.3.1
6 info lifecycle extract-file-icon@0.3.1~rebuild: extract-file-icon@0.3.1
7 verbose lifecycle extract-file-icon@0.3.1~rebuild: unsafe-perm in lifecycle true
8 verbose lifecycle extract-file-icon@0.3.1~rebuild: PATH: C:\Users\clifford\AppData\Roaming\nvm\v12.2.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\clifford\Desktop\test-windows-icon-generator\node_modules\extract-file-icon\node_modules\.bin;C:\Users\clifford\Desktop\test-windows-icon-generator\node_modules\.bin;C:\Users\clifford\AppData\Roaming\nvm\v12.2.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\clifford\Desktop\test-windows-icon-generator\node_modules\extract-file-icon\node_modules\.bin;C:\Users\clifford\Desktop\test-windows-icon-generator\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Users\clifford\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\ProgramData\osquery;C:\Program Files (x86)\Yarn\bin\;C:\Users\clifford\AppData\Local\Microsoft\WindowsApps;C:\Users\clifford\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\clifford\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\clifford\AppData\Local\JetBrains\DataGrip 2019.1.2\bin;;C:\Users\clifford\AppData\Local\Yarn\bin
9 verbose lifecycle extract-file-icon@0.3.1~rebuild: CWD: C:\Users\clifford\Desktop\test-windows-icon-generator\node_modules\extract-file-icon
10 silly lifecycle extract-file-icon@0.3.1~rebuild: Args: [ '/d /s /c', 'node-gyp rebuild' ]
11 silly lifecycle extract-file-icon@0.3.1~rebuild: Returned: code: 1  signal: null
12 info lifecycle extract-file-icon@0.3.1~rebuild: Failed to exec rebuild script
13 verbose stack Error: extract-file-icon@0.3.1 rebuild: `node-gyp rebuild`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\clifford\AppData\Roaming\nvm\v12.2.0\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:196:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\clifford\AppData\Roaming\nvm\v12.2.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:196:13)
13 verbose stack     at maybeClose (internal/child_process.js:1011:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
14 verbose pkgid extract-file-icon@0.3.1
15 verbose cwd C:\Users\clifford\Desktop\test-windows-icon-generator\node_modules\extract-file-icon
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
18 verbose node v12.2.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error extract-file-icon@0.3.1 rebuild: `node-gyp rebuild`
22 error Exit status 1
23 error Failed at the extract-file-icon@0.3.1 rebuild script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
</details>

**Comment by sentialx** [comment]
Try to run `npm i -g windows-build-tools` as administrator.

> I could see this dependency being problematic if this a package is used in an electron app, which tries to call this package on a Windows computer that doesn't have python installed.

It doesn't work this way. The package needs the build tools only for building Electron apps. End users just open the compiled exe.
